import { EcosystemApp } from "./types";

export const ECOSYSTEM_APPS: EcosystemApp[] = [
  {
    id: "metaphor",
    name: "Metaphor OS",
    codename: "Cognitive Context Engine",
    tagline: "Universal context graph & multi-tenant sovereign intelligence",
    category: "context",
    iconName: "Metaphor",
    accentColor: "#4E6CF2",
    glowColor: "rgba(78, 108, 242, 0.3)",
    status: "live",
    defaultUrl: "https://metaphor-three.vercel.app",
    localPort: 3000,
    description: "The neural brain of your entire ecosystem.",
    features: ["Universal Memory Graph", "Context Layer Playground", "Autonomous MCP Gateway", "Semantic Vector Store"],
    permissions: ["read:context", "write:context", "manage:memory", "read:profile"],
    sessionStatus: "connected",
    lastSync: "Just now"
  },
  {
    id: "orion",
    name: "Orion",
    codename: "William Mobile",
    tagline: "High-fidelity Skia neural mobile client & audio reflection stream",
    category: "agentic",
    iconName: "Orion",
    accentColor: "currentColor",
    glowColor: "rgba(17, 19, 24, 0.3)",
    status: "building",
    defaultUrl: "https://william-web-zeta.vercel.app",
    localPort: 8081,
    description: "Your sovereign companion in your pocket.",
    features: ["Liquid Skia Orb", "Realtime Audio Visualizer", "Executive Dock", "Offline Sync Cache"],
    permissions: ["read:profile", "stream:voice", "write:context", "read:notifications"],
    sessionStatus: "connected",
    lastSync: "2 mins ago"
  },
  {
    id: "atlas",
    name: "Atlas",
    codename: "Demand Generation Engine",
    tagline: "AI agency operating system, multi-channel outreach & CRM pipeline",
    category: "growth",
    iconName: "Atlas",
    accentColor: "#4E6CF2",
    glowColor: "rgba(78, 108, 242, 0.3)",
    status: "live",
    defaultUrl: "https://atlas-scale.vercel.app",
    localPort: 5173,
    description: "The commercial heartbeat.",
    features: ["Pipeline CRM", "Lead Enrichment & Discovery", "Automated Email Sequences", "Smart Proposal Generator"],
    permissions: ["read:profile", "manage:leads", "write:pipeline", "read:context"],
    sessionStatus: "connected",
    lastSync: "5 mins ago"
  },
  {
    id: "clario",
    name: "Clario",
    codename: "Creative Studio & Media Synthesizer",
    tagline: "High-impact video canvas, asset orchestration & neural creative engine",
    category: "creative",
    iconName: "Clario",
    accentColor: "#ec4899",
    glowColor: "rgba(236, 72, 153, 0.3)",
    status: "live",
    defaultUrl: "http://localhost:49843",
    localPort: 49843,
    description: "Next-gen multimedia workspace.",
    features: ["Procedural Video Canvas", "Dynamic Asset Grid", "AI Prompt Matrix", "Audio Spectrum Analyzer"],
    permissions: ["read:profile", "write:media", "read:context", "export:renders"],
    sessionStatus: "connected",
    lastSync: "12 mins ago"
  },
  {
    id: "weave",
    name: "Weave",
    codename: "Agentic Mesh & Workflow Fabric",
    tagline: "Autonomous distributed agent swarm orchestrator",
    category: "agentic",
    iconName: "Weave",
    accentColor: "#f59e0b",
    glowColor: "rgba(245, 158, 11, 0.3)",
    status: "planned",
    defaultUrl: "http://localhost:3003",
    localPort: 3003,
    description: "Low-latency event fabric tying background agents together.",
    features: ["Swarm Orchestration", "Async Event Bus", "Tool Calling Routing", "Telemetry Dash"],
    permissions: ["read:profile", "execute:agents", "read:vault", "write:vault"],
    sessionStatus: "standby",
    lastSync: "Pending deployment"
  },
];
